package modelo;
// Generated 25/05/2020 06:09:41 PM by Hibernate Tools 4.3.1



/**
 * Mascota generated by hbm2java
 */
public class Mascota  implements java.io.Serializable {


     private int idMascota;
     private String nombre;
     private String nombreDueno;
     private String raza;
     private int edad;

    public Mascota() {
    }

    public Mascota(int idMascota, String nombre, String nombreDueno, String raza, int edad) {
       this.idMascota = idMascota;
       this.nombre = nombre;
       this.nombreDueno = nombreDueno;
       this.raza = raza;
       this.edad = edad;
    }
   
    public int getIdMascota() {
        return this.idMascota;
    }
    
    public void setIdMascota(int idMascota) {
        this.idMascota = idMascota;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreDueno() {
        return this.nombreDueno;
    }
    
    public void setNombreDueno(String nombreDueno) {
        this.nombreDueno = nombreDueno;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }




}


